apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-app
  labels:
    app: food-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-app
  template:
    metadata:
      labels:
        app: food-app
    spec:
      containers:
      - name: frontend
        image: public.ecr.aws/w8m9e4i1/foodapp-frontend:v1
        ports:
        - containerPort: 8080

      - name: backend
        image: public.ecr.aws/w8m9e4i1/foodapp-backend:v1
        ports:
        - containerPort: 8081

      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "demo"
        - name:  MYSQL_DATABASE
          value: "db_restaurant"
        - name: MYSQL_USER
          value: "dbuser"
        - name:  MYSQL_PASSWORD
          value: "demo"

        ports:
        - containerPort: 3306
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: food-app-service
# spec:
#   selector:
#     app: food-app
#   ports:
#   - name: http
#     port: 8080
#     targetPort: 3000

